### ISSUE TITLE
Migrate UTD Grades from AWS to Google Cloud deployment

### ISSUE THREAD

**Issue by WillieCubed** [UTDNebula/utd-grades#25]
# Overview

Right now, the UTD Grades back-end [functions](https://github.com/UTDNebula/utd-grades/tree/master/functions) are deployed to AWS Lambda using the acmutdlabs AWS root account. However, all other Project Nebula products use Google Cloud Platform, which integrates with our existing IAM solution (Google Workspace). Although UTD Grades is soon to be deprecated, it may need to exist in a backup form for our intended March 25, 2022 target for its deprecation and may need to stay up. Furthermore, redeploying to Google Cloud may give us the opportunity to reduce costs in the meantime, which may give more funding to other parts of the Project Nebula budget. As such, we should redeploy the service to use GCP resources.

# Tasks

- [ ] Ensure that the UTD Grades backend is properly containerized
- [ ] Deploy the UTD Grades functions container to Google Cloud Run or equivalent
- [ ] Configure settings to auto-scale the container to reduce resource usage when client request volume is low

**Comment by CharlieMahana** [comment]
If we're about to rewrite this entire platform, why should I spend my time migrating everything if we're just trying to limp it through the final stages of deprecation before we deploy the new platform? Seems like a massive waste of time to me.

**Comment by WillieCubed** [comment]
This is not happening.
